version: "2"
services:
  serv1:
    build: ./Service1
    depends_on:
      - "rabbit"
    volumes:
      - ./indir:/project/outdir
  rabbit:
    hostname: rabbit
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  serv2:
    build: ./Service2
    depends_on:
      - "rabbit"
    volumes:
      - ./outdir:/project/outdir

  
  
